#!/bin/bash
#Funnyvpn
#Rerechan02
#Rayzell25
#Nuralfiya
#em0zz
#naravpn.com
#indo-ssh.com
#indossh
#Skc
clear
#=========================================================================================================================
#Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
#INPUT SSH
domain=$(cat /etc/xray/domain)
clear
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[40;1;37m            SSH Account            \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (Days): " masaaktif
clear
systemctl restart ws-stunnel
systemctl restart ws-nontls
systemctl restart dropbear
systemctl restart ssh
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e ""
clear
echo -e "══════════════════════════"
echo -e "    <=  SSH ACCOUNT =>"
echo -e "══════════════════════════"
echo -e ""
echo -e "Username     : $Login"
echo -e "Password     : $Pass"
echo -e "Host/IP      : $(cat /etc/xray/domain)"
echo -e "Udp Custom   : 1-65535"
echo -e "Port ssl/tls : 443"
echo -e "Port non tls : 80, 2082, 8080"
echo -e "Udpgw/Badvpn : 7200"
echo -e ""
echo -e "══════════════════════════"
echo -e "Payload Ws   => GET / HTTP/1.1[crlf]Host: $(cat /etc/xray/domain)[crlf]Upgrade: websocket[crlf][crlf]"
echo -e "══════════════════════════"
echo -e "     Expired => $expi"
echo -e "══════════════════════════"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
